### ISSUE TITLE
Reload only occurs once if script tag in head

### ISSUE THREAD

**Issue by mfikes** [bhauman/figwheel-main#102]
Here is a minimal repro that exhibits that reloading works once, but not for subsequent file changes.

Files:

`deps.edn`:

```clojure
{:paths   ["src" "target" "resources"]
 :deps    {org.clojure/clojurescript {:mvn/version "1.10.339"}
           com.bhauman/figwheel-main {:mvn/version "0.1.9"}}
 :aliases {:repl  {:main-opts ["-m" "figwheel.main" "-b" "base" "-r"]}}}
```

`base.cljs.edn`:

```clojure
{:output-to    "resources/public/js/main.js"
 :main         "foo.core"}
```

`resources/public/index.html`:

```html
<html>
<head>
  <script type="text/javascript" src="js/main.js"></script>
</head>
</html>
```

`src/foo/core.cljs`:

```clojure
(ns foo.core)

(def a 1)
```

1. Start the REPL via `clojure -A:repl`
2. Evaluate `foo.core/a` and see that it evaluates to `1`.
3. In another terminal, edit `src/foo/core.cljs` and add `(def b 2)`
4. Save the edit and observe that recompilation occurs.
5. Confirm the change by evaluating `foo.core/b` and seeing that it evaluates to `2`.
6. Edit `src/foo/core.cljs` and add `(def c 3)`
7. Save the edit and observe that recompilation occurs.
8. Attempt to confirm the change by evaluating `foo.core/c`, but instead of `3` observe that you get `nil`.

This occurs on macOS with Safari and also with Chrome.

**Comment by bhauman** [comment]
@mfikes this is caused by placing the script in `<head>`

**Comment by bhauman** [comment]
This is not the recommended practice. But I do count this as a bug.

**Comment by mfikes** [comment]
Ahh, OK. I simply added a `body` open close pair and that was insufficient. But then moving the `script` tag into the body did the trick:

```html
<html>
<head>
</head>
<body>
  <script type="text/javascript" src="js/main.js"></script>
</body>
</html>
```

**Comment by bhauman** [comment]
Yeah fixed here https://github.com/bhauman/figwheel-core/commit/396079cbe4a74bd20455cafc0a1872a032ebcf56

**Comment by mfikes** [comment]
Thanks Bruce. I've confirmed that this fix works for me for this issue as written, and also fixes the same sort of problem for me in a more complicated downstream project (which has the `script` tag in the `head`).

**Comment by bhauman** [comment]
Great!! And thanks for the shout out :)
