### ISSUE TITLE
fix modules behavior

### ISSUE THREAD

**Issue by bhauman** [bhauman/figwheel-main#11]
Make it so that :modules cljs_base is loaded on the default repl pages.

Make it so that we print out the correct artifacts that are being compiled.

Remove `:main` and `:ouput-to` when using modules as they do not apply.

**Comment by DjebbZ** [comment]
Maybe warn user that they should include :modules cljs-base and/or others themselves. You can't know in advance if their code will need all :modules to run, only cljs-base or a few.

**Comment by bhauman** [comment]
added basic support for modules here: https://github.com/bhauman/figwheel-main/commit/4101a63e8455463d5288e5e035c143d09e2a4b80
