### ISSUE TITLE
Error connecting to vim-fireplace with non default output paths

### ISSUE THREAD

**Issue by Jens-H** [bhauman/figwheel-main#115]
I guess this problem should be fixed by vim-fireplace, but figwheel has a very good documentation (https://figwheel.org/docs/vim.html) and maybe a warning there would be appropriate. To be clear: The example in the docs is working, but as soon as I start figwheel with different output-to, output-dir and asset-path options, I cannot connect in vim anymore. The error is "FileNotFoundException out/js-environment.log [...]".

I believe the problem is, that vim-fireplace's function :Piggieback is wrapping around some more Clojure code and in the end the result is something like this:

((or (resolve 'cider.piggieback/cljs-repl) (resolve 'cemerick.piggieback/cljs-repl)) (figwheel.main.api/repl-env "dev"))

It looks like the cider.piggieback/cljs-repl doesn't behave similar to figwheel.main.api/cljs-repl and therefore expects the (default) out dir (see error message), cannot find it and then fails.

Maybe some feedback how vim-fireplace should ideally call figwheel would help. I tried (figwheel.main.api/cljs-repl "dev") which seems to work.

**Comment by bhauman** [comment]
OK I fixed this and I'm pushing it to 0.2.1-SNAPSHOT right now. Please test this and let me know if its working.

**Comment by Jens-H** [comment]
Great. I tested it with one project and it looks alright now.

**Comment by Jens-H** [comment]
Thanks for the fix!
