### ISSUE TITLE
How to run multiple independent builds?

### ISSUE THREAD

**Issue by isker** [bhauman/figwheel-main#123]
Hi!  I'm trying to understand how to achieve the equivalent of running multiple lein-figwheel `:cljsbuild { :builds { ... } }` in figwheel-main.  If it helps for context, I'm going for the equivalent of [this chrome extension lein-figwheel setup](https://github.com/binaryage/chromex-sample/blob/e9ada411456265e214c6605f6c25a4b35ef302f8/project.clj#L27), where independent sets of inputs and outputs are built at once by figwheel.

Using multiple `--build`s (e.g. `-b background:popup`, if those 2 config files exist) does not work as they are merged together, so practically `popup` clobbers `background`.

Is there a way to get what I'm describing?

Thanks!

**Comment by bhauman** [comment]
look at the `-bb` and the extra mains options.

https://figwheel.org/docs/extra_mains.html
https://figwheel.org/docs/background_builds.html

**Comment by isker** [comment]
Thanks!  I'll go ahead and close this.
