### ISSUE TITLE
test-runner hanging with advanced optimizations 

### ISSUE THREAD

**Issue by henryw374** [bhauman/figwheel-main#125]
Hi,

I'd like to run tests with advanced optimizations in order to find externs problems etc before deployment. However, adding that compiler opt causes the test runner to hang. 

Thanks,
Henry

**Comment by bhauman** [comment]
Yes the test runner does not currently support advanced compilation, as it is intended for live updates.
for advanced to work you would need to setup a single test run.

**Comment by henryw374** [comment]
ok, Thanks for the info.
