### ISSUE TITLE
Figwheel-main + vim-fireplace + piggieback doesn't pass :output-dir to the CLJS REPL correctly

### ISSUE THREAD

**Issue by krajj7** [bhauman/figwheel-main#145]
Following the [setup guide for Figwheel-main + Vim](https://github.com/bhauman/figwheel-main/blob/master/docs/docs/vim.md), I believe there is a problem with passing the :output-dir option (:target-dir of the build config) to the CLJS REPL when it is launched from Piggieback. This causes evaluations from Piggieback to create JS code in the default "out" directory, instead of respecting the :target-dir option for the build.

This doesn't always cause errors if the target-dir also contains all the necessary JS, but I think the appearance of the "out" directory when you call `:Piggieback ...` from vim is evidence of the problem.

I'll try to make it more clear by comparing with the old lein-figwheel + figwheel-sidecar, where this problem doesn't occur.

To connect to the old lein-figwheel CLJS REPL, you would do (after starting the build)
`:Piggieback (figwheel-sidecar.api/repl-env)`
which ends up launching
`(cider.piggieback/cljs-repl (figwheel-sidecar.api/repl-env))`

Now with figwheel-main we start the build and do
`:Piggieback (figwheel.main.api/repl-env "my-build")`
which ends up launching
`(cider.piggieback/cljs-repl (figwheel.main.api/repl-env "my-build"))`

The problem is the new `(figwheel.main.api/repl-env "my-build")` object isn't passing repl-options correctly (including :output-dir), which can be checked by comparing:

```clojure
(keys (cljs.repl/-repl-options (figwheel-sidecar.api/repl-env)))
=> (:output-dir :wrap :compiler-env :special-fns :optimizations :preloads :output-to :source-map-timestamp :prompt :asset-path :warn-on-undeclared :main :eval)
```

vs. with fighwheel-main:

```clojure
(keys (cljs.repl/-repl-options (figwheel.main.api/repl-env "my-build")))
=> (:preloads :cljs.cli/commands :cljs.cli/main)
```

Absence of the :output-dir key here makes the REPL put code in the default "out" directory. The new `figwheel.main.api/repl-env` object does actually contain the :output-dir key at the root level, but `cider.piggieback/cljs-repl` is not looking for it there. This option could also be passed as an extra option argument to `cider.piggieback/cljs-repl`, but I think there is no way to do that by doing `:Piggieback ...` from vim, while the implementation of -repl-options could be changed to return it like figwheel-sidecar does.

The other repl-options might also be affected, but I only noticed problems with :output-dir.

**Comment by Jens-H** [comment]
Looks like the issue I raised some time ago #115

**Comment by bhauman** [comment]
Thank you for your thorough analysis. I'm working on this right now.

**Comment by bhauman** [comment]
OK I fixed this and I'm pushing it to 0.2.1-SNAPSHOT right now

**Comment by torgeir** [comment]
Had a similar issue with vscode+calva connecting for a cljs repl through piggieback. Temporarily resolved by using the following snippet for connecting from vscode

```clj
(do
  (require '[cider.piggieback :refer [cljs-repl]]
           '[figwheel.main.api :refer [repl-env]])
  (cljs-repl (repl-env "dev") :output-dir “target/public/cljs-out/dev”))
```

(`Settings -> Extensions -> Calva -> Calva: Start CLJSREPLCommand`)

**Comment by bhauman** [comment]
I've not had a response on whether the SANPSHOT fix worked for this.

**Comment by krajj7** [comment]
Sorry about the delayed feedback. I can confirm that with `0.2.1-SNAPSHOT` the problem no longer occurs. Thank you for the fix.

**Comment by SevereOverfl0w** [comment]
I also had a related issue with `:foreign-libs` which this appears to have resolved.
