### ISSUE TITLE
The :warnings cljs compiler option is ignored

### ISSUE THREAD

**Issue by jacobobryant** [bhauman/figwheel-main#146]
Steps to reproduce:

1. Create new project with `lein new figwheel-main foo`
2. Create a new file `foo/src/foo.cljs` with contents `(ns foo)`
3. In `foo/dev.cljs.edn`, add `:warnings {:single-segment-namespace false}` to the cljs options
4. From `foo/`, run `lein fig:build`
5. After figwheel finishes loading the web page, make an edit to a file (e.g. `foo.cljs`)
6. Observe from the web page that the single segment namespace error still shows in the console and on the heads up display and that the file you edited doesn't get reloaded.

This still occurs if I update the figwheel-main version from 0.1.9 to 0.2.0.
Also, I believe this is a bug with figwheel and not cljs because I was able to
get these results:

```
$ mkdir /tmp/foo && cd /tmp/foo
$ mkdir src
$ cat > src/foo.cljs
(ns foo)
$ cat > deps.edn
{:deps {org.clojure/clojurescript {:mvn/version "1.10.339"}}}
$ clj --main cljs.main --compile foo
WARNING: foo is a single segment namespace at line 1 /tmp/foo/src/foo.cljs
$ rm -r out/
$ clj --main cljs.main -co "{:warnings {:single-segment-namespace false}}" --compile foo
$ # no output; the compile finishes without warnings
```

I haven't tested with other cljs warnings, but I have tried `:warnings false` which still has no effect. The `:load-warninged-code true` figwheel option does work at least; so there's a workaround.

If you have a hunch about what's going on and could point me in the right direction, I'd be happy to work on a PR.

**Comment by bhauman** [comment]
This is fixed in 0.2.1-SNAPSHOT
