### ISSUE TITLE
Evaluation timeout due to websocket message size limit 

### ISSUE THREAD

**Issue by fdserr** [bhauman/figwheel-main#154]
Using Figwheel browser REPL to evaluate an expression that results in a value exceeding 64kb when serialised doesn't return. The REPL will just print "Eval Timed out" after a while.

**Comment by fdserr** [comment]
FIXED by https://github.com/bhauman/figwheel-repl/pull/3

**Comment by tomvdsom** [comment]
If I'm not mistaken, the issue is fixed in `figwheel-repl`, but still occurs since a new release has to be publish in Clojars including this (& the `figwheel-main` deps updated).

Almost there ... 😄
