### ISSUE TITLE
pprint-config vs print-config

### ISSUE THREAD

**Issue by mmuallem** [bhauman/figwheel-main#155]
It came to my attention that there seems to be a mismatch between the `fighweel.main` options and documentation regarding printing configuration.

Everywhere in the documentation, printing config option is referred to as `ppring-config`, which does make sense. But, in v0.2.0, the actual option is `print-config`, with a single `p`.

In fact, running `fighweel.main` with `--pprint-config` [as stated int he README], prints out:

```
Error in command line args
-- Misspelled CLI flag ------------

  ["--pprint-config"]
   ^^^^^^^^^^^^^^^^^

should probably be: "--print-config"

__ Doc for -pc --print-config _____

  Instead of running the command print out the configuration built
  up by the command. Useful for debugging.

-------------------------
Detected 1 error
```

Should the README be updated? or the option reverted back to `pprint-config`?
I would happily submit a PR for either.

**Comment by bhauman** [comment]
Thanks! just fixed this.

25f1152c0c80ce0f219246d3d5b33508f23ba014
