### ISSUE TITLE
Failing compiling with `lein fig:min` on windows 10

### ISSUE THREAD

**Issue by adicirstei** [bhauman/figwheel-main#157]
Hi, although the `lein fig:build` is working fine out of the box, when I try to compile with `lein fig:min` or manually expanding the alias as `lein run -m figwheel.main -O advanced  -bo dev` I get the below error:

```
[Figwheel] Validating figwheel-main.edn
[Figwheel] figwheel-main.edn is valid \(?)/
[Figwheel] Compiling build dev to "resources\public\cljs-out\dev-main.js"
[Figwheel] Failed to compile build dev in 5.271 seconds.
[Figwheel] Compile Exception: Illegal char <:> at index 2: /D:/projects/clojure/welcome/resources/public/cljs-out/dev/cljs/core.js
[Figwheel:SEVERE] java.nio.file.InvalidPathException: Illegal char <:> at index 2: /D:/projects/clojure/welcome/resources/public/cljs-out/dev/cljs/core.js
```

The project is the minimal one generated by `figwheel-main-template`. The config as printed by `lein run -m figwheel.main -O advanced -pc -bo dev` command is:

```text
[Figwheel] Validating figwheel-main.edn
[Figwheel] figwheel-main.edn is valid \(?)/
---------------------- Figwheel options ----------------------
[Figwheel] :pprint-config true - printing config:
{:target-dir "resources",
 :pprint-config true,
 :figwheel.main/build-once true,
 :watch-dirs ("test" "src"),
 :css-dirs ["resources/public/css"],
 :auto-testing true,
 :figwheel.main/build-inputs
 [#object[java.net.URL 0x6e54bef6 "file:/D:/projects/clojure/welcome/src/welcome/core.cljs"]]}
---------------------- Compiler options ----------------------
{:optimizations :advanced,
 :main welcome.core,
 :output-to "resources\\public\\cljs-out\\dev-main.js",
 :output-dir "resources\\public\\cljs-out\\dev",
 :asset-path "/cljs-out/dev",
 :aot-cache false}
````

I wanted to handle the issue my self but got lost in the source code. 
Thanks!

**Comment by bhauman** [comment]
yeah the :build-inputs seems to be choking on the windows path somehow.

I think this is caused around this line in the source code:

https://github.com/bhauman/figwheel-main/blob/master/src/figwheel/main.cljc#L1414

I think I'm not accounting to windows there.

**Comment by adicirstei** [comment]
Is there any document describing how to hook into it in order to debug it?

**Comment by jc776** [comment]
I don't think this is figwheel-specific, same path issue is still open on both CLJS and closure-compiler:
https://clojure.atlassian.net/browse/CLJS-2401
https://github.com/google/closure-compiler/issues/2611

I can reproduce this by doing a non-optimized compile before doing an advanced compile.
I don't get the problem if I delete target before doing an advanced compile.
There's some mention of 'I think this is fixed' in the closure-compiler issue, but I still get the issue with CLJS 1.10.520.
Minimal config (clj, not lein!) with the output of those cases here: https://github.com/jc776/fw157compile

**Comment by adicirstei** [comment]
Thanks for the workaround, @jc776 . 
BTW, I had to delete `resources\public\cljs-out\` folder, not `target`.
I will close the issue.
