### ISSUE TITLE
Not Public Warnings

### ISSUE THREAD

**Issue by pwhittin** [bhauman/figwheel-main#160]
After I add the following deps:
    day8.re-frame/re-frame-10x      {:mvn/version "0.3.7-react16"}
    day8.re-frame/tracing           {:mvn/version "0.5.1"}

I get the following warnings during compile:

[Figwheel:WARNING] Compile Warning   resources/public/cljs-out/dev/rewrite_clj/reader.cljs   line:181  col
umn:14                                                                 
                                                                                   
  var: cljs.tools.reader/read-token is not public                                
                       
  176          (aget matches 0)                                                  
  177          matches))))                                                            
  178                                                                                              
  179  (defn read-keyword         
  180    [^not-native reader initch]
  181    (let [tok (cljs.tools.reader/read-token reader :keyword (read-char reader))
                    ^--- 

and

[Figwheel:WARNING] Compile Warning   resources/public/cljs-out/dev/rewrite_clj/parser/core.cljs   line:14$
  column:10

  var: rewrite-clj.reader/whitespace? is not public

  144  
  145  (defn- dispatch
  146    [c]
  147    (cond (nil? c)                        parse-eof
  148          (identical? c *delimiter*)      reader/ignore
  149          (reader/whitespace? c)          parse-whitespac

**Comment by bhauman** [comment]
This is a dependency problem that is outside the scope of figwheel-main.

Sorry for the brevity but I'm on vacation :)
