### ISSUE TITLE
Clojure errors cause the REPL to hang

### ISSUE THREAD

**Issue by sirmspencer** [bhauman/figwheel-main#161]
To replicate launch figwheel from the terminal, type `(deref imnotarealatom)` and it will show an error:
```
Compile Warning   <cljs repl>   line:1  column:8

  Use of undeclared Var cljs.user/anything

  1  (deref anything)
            ^---

#object[Error Error: No protocol method IDeref.-deref defined for type undefined: ]
```

I now cannot enter any new commands to the repl.  

My figwheel .edn
```
{:watch-dirs ["src/cljs"]
 :ring-server-options {:port 8080 :join? false}
 :ring-handler carbon-tool.handler/development-app}
```
and my clojure .edn
```
{:paths ["src/clj" "src/cljs" "resources" "target"]

 :deps {org.clojure/clojure       {:mvn/version "1.10.0"}
        ring/ring                 {:mvn/version "1.7.1"}
        ring/ring-defaults        {:mvn/version "0.3.2"}
        bidi/bidi                 {:mvn/version "2.1.5"}
        hiccup/hiccup             {:mvn/version "2.0.0-alpha2"}
        org.clojure/data.json     {:mvn/version "0.2.6"}
        org.clojure/java.jdbc     {:mvn/version "0.7.9"}
        org.postgresql/postgresql {:mvn/version "42.2.5"}
        org.clojure/clojurescript {:mvn/version "1.10.520"}
        reagent/reagent           {:mvn/version "0.9.0-SNAPSHOT"}
        herb/herb                 {:mvn/version "0.7.2"}}

 :aliases {:figwheel     {:extra-deps {com.bhauman/figwheel-main {:mvn/version "0.2.1-SNAPSHOT"}
                                       com.bhauman/rebel-readline-cljs {:mvn/version "0.1.4"}}
                          :main-opts ["-m" "figwheel.main" "-b" "compile-dev" "-r"]}}}
```

OS Ubuntu 18.10.  Confirmed on other non-debian linux distros on my team.

**Comment by bhauman** [comment]
Is this only a problem when you use rebel-readline? Try removing the rebel-readline dep.

**Comment by sirmspencer** [comment]
Removing rebel-readline does not help

**Comment by bhauman** [comment]
Thanks for giving it a try.

**Comment by aszenasi** [comment]
I have the same problem.
Here is stacktrace:
	at clojure.pprint$pprint.invoke(pprint_base.clj:241)
	at figwheel.main$repl_caught$fn__7380.invoke(main.cljc:1547)
	at figwheel.main$repl_caught.invokeStatic(main.cljc:1547)
	at figwheel.main$repl_caught.invoke(main.cljc:1535)

When i (set! *print-level* 10), the problem solved.
I hope this helps.

**Comment by Outrovurt** [comment]
I have the same issue, which I had posted to the rebel-readline issues page here:

[https://github.com/bhauman/rebel-readline/issues/197](url)

I've just carried out some further diagnostics and it seems to be a figwheel-main issue. I tried removing rebel-readline as a dependency from fighweel-main (using :exclusions), however that didn't work.

What did work for me was rolling back to an earlier version of figwheel-main. I was previously running 0.2.3 (the latest at this time I believe), however I had to rollback to 0.2.0 and that solved the problem.

The strange thing is that as far as I can tell, nothing changed whatsoever in my config or setup which could have caused this error to start happening. I was running on 0.2.3 for some months and I haven't updated anything else. It just spontaneously started happening one day.

Something else weird which started happening around the same time was that I was started seeing "This site can't provide a secure connection" in Chrome whenever I tried to access my project, which is currently running a devcards setup. This usually happens in the morning (don't ask why, I'm stumped on that) and I usually have to restart figwheel and clear the browser cache to get it to work again.

I tried aszenasi's fix, which I assume means (set! *print-level* 10), but that didn't work. Rolling back to 0.2.0 was the only thing that fixed it. Hope this helps someone.

**Comment by Outrovurt** [comment]
Ah, bugger: this does of course mean losing all the features introduced in between :-(

**Comment by fdserr** [comment]
Bump please?

Same issue here since upgrading to 2.3. Not using rebel.

Also, when this happens the java process gets crazy after a while.

**Comment by Outrovurt** [comment]
@fdserr,

What do you mean by "the java process gets crazy after a while"? Can you describe it, or paste any error messages you see when this happens?

I stayed on 0.2.0 and to be honest with you the only feature that I lost was the ability to use pprint from the REPL. No big deal as instead I use the CLJS DevTools [https://github.com/binaryage/cljs-devtools]. This produces slightly different log messages than pprint, but once you get used to using it they are actually more useful.

As such I would recommend just using 0.2.0.

**Comment by bhauman** [comment]
I finally found the source of this bug and fixed it here:
https://github.com/bhauman/figwheel-repl/commit/cab3cbb5df6060caf0a04364f93a0ba3f151cf80

**Comment by sirmspencer** [comment]
@bhauman I see you bumped the version to 2.4-SNAPSHOT to include this change.  Do you have plans to post this version on the repo?

**Comment by pyrmont** [comment]
For those using `deps.edn` to manage dependencies, you can use [a temporary fork](https://github.com/pyrmont/figwheel-main/commit/bfb80e9de31baddae4f2eb886f631d45dfd9e43e) I've made of figwheel-main that is otherwise identical to current master but for the fact it replaces the references in figwheel-main's `deps.edn` to figwheel-repl's and figwheel-core' GitHub repositories.

Just change:
```edn
com.bhauman/figwheel-main {:mvn/version "0.2.3"}}
```
to:
```edn
com.bhauman/figwheel-main {:git/url "https://github.com/pyrmont/figwheel-main" :sha "bfb80e9de31baddae4f2eb886f631d45dfd9e43e"}
```

Seems to be working great so far!
