### ISSUE TITLE
Hot reload of code breaks source maps

### ISSUE THREAD

**Issue by rnikander** [bhauman/figwheel-main#163]
I start figwheel, it compiles the code, and I load my page in the browser. I debug the JS and I see a stacktrace with cljs files, as expected. 

But if I edit a file, figwheel compiles it, hot reloads the code, and I go to debug... now I see a stacktrace with the js versions of my cljs files, which is of course much less useful.

I'm using Safari 12.0.3 or macOS.

**Comment by rnikander** [comment]
Same seems to go for exception stack traces in the JS console.

**Comment by bhauman** [comment]
This is a known defect in Browsers. We've done everything we can from our end to assist browsers to do the right thing.   Google Chrome fixed this a ways back... So an answer here is to use Google Chrome.
