### ISSUE TITLE
Can't take value of macro on reloading with CLJS 1.10.449+

### ISSUE THREAD

**Issue by timothypratley** [bhauman/figwheel-main#165]
Steps to reproduce:

`clj -A:new figwheel-main hello-world.core -- --reagent`

Make sure CLJS dependency is 1.10.449 or higher

Add a function:
```
(defn f []
  (when (exists? js/Localize)
    (println "Localize exists")))
```

When saving further changes:

Compile Warning /Users/timothy/git/hello/src/hello_world/core.cljs
**Can't take value of macro cljs.core/exists?**
```
 7  (defn f []
 8    (when (exists? js/Localize)
             ^--- Can't take value of macro cljs.core/exists?
 9      (println "Localize exists")))
```

Example project attached:
[hello.zip](https://github.com/bhauman/figwheel-main/files/3119024/hello.zip)

Expected:

Should not be a warning.

Additional information:

**Note also that initial compilation succeeds with no warnings.**

This only started happening since CLJS 1.10.449, prior to that it does not occur. As such it is definitely related to CLJS core, however CLJS has a policy of not accepting bug reports in tools. I do not know how to reproduce this in CLJS without figwheel.main being present. Any advice on how to do that would be greatly appreciated.

See also: https://cljs.github.io/api/cljs.core/existsQMARK

**Comment by mfikes** [comment]
I suspect this is an instance of failed warning suppression, which is fixed with https://github.com/bhauman/figwheel-core/pull/2

**Comment by timothypratley** [comment]
@mfikes Thank you. I confirmed your suspicion by adding figwheel-core 0.2.1-SNAPSHOT as a dependency and the warnings are not present. Next release will resolve this issue.
