### ISSUE TITLE
How about a Figwheel logo?

### ISSUE THREAD

**Issue by PEZ** [bhauman/figwheel-main#178]
Hello,

I am soon going to release a new version of Calva, with better, and more direct, support for Figwheel Main. Calva will then also have an integrated REPL window, much inspired by CIDER. 

A thing with Calva is that it should be easy to know which REPL server is evaluating your code. And to that aim I am decorating the REPL window with images showing if it is a Clojure or ClojureScript REPL. And also I want to show what kind of CLJS repl. It looks like so for shadow-cljs:

<img width="504" alt="image" src="https://user-images.githubusercontent.com/30010/57199918-1b3fa480-6f85-11e9-82b6-e28ac5da7e8f.png">

But.I don't know what to show there for lein-figwheel and Figwheel Main. Have you considered some logos/symbols? This is a request for such artwork.

Regards,

/Peter

**Comment by DogLooksGood** [comment]
emmmm, looks like there's something looks like a logo on the top left of this home page.
https://figwheel.org/docs/code_splitting.html

**Comment by timothypratley** [comment]
Yup, looks like ![](https://figwheel.org/assets/images/navar-logo.svg) has it covered :)
