### ISSUE TITLE
Tutorial - No REPL lauched

### ISSUE THREAD

**Issue by davidsavoie1** [bhauman/figwheel-main#185]
Firs of all, thanks a lot for the nice [tutorial](https://figwheel.org/tutorial). It's exactly what I need to try and learn clojure/script basics and tooling.

However, when I launch figwheel with `clj -m figwheel.main`, a browser window opens correctly, but the terminal never completes to show a REPL. It stops at the line `Opening URL http://localhost:9500`, and no `cljs.user=>` prompt ever appears.

I'm using Chrome on Linux in a standard shell. I tried removing rebel-readline from dependencies, without difference. Thanks in advance!

EDIT: By the way, the browser succesfully connects to the REPL, as indicated by the green "Connected" next to the logo...

**Comment by davidsavoie1** [comment]
I've discovered that the REPL prompt appears if I launch the `clj -m figwheel.main` command and there is already a Google Chrome window open. If the command opens a new window itself, the REPL prompt never becomes accessible... Very strange!

**Comment by cavandavid** [comment]
I see the exact same thing with the exact fix working too. I'm sure there's an explanation for this...
