### ISSUE TITLE
Change compile directory

### ISSUE THREAD

**Issue by AkashHC13** [bhauman/figwheel-main#189]
I'm trying to move from `lein-figwheel` to `figwheel-main` and I'm using lein.
By default `figwheel-main` compiles the build and puts it in `target/public/cljs-out` directory.
However I wanted it to be in a different location `resources/public/js/`. 
I tried adding `compile-path` and the `target-path` in my project.clj and nothing is getting changed. 
Can't the compile path be modified @bhauman ? If it can be modified how can I do that?

**Comment by bhauman** [comment]
I believe you want ‘:target “resources/public”’

**Comment by AkashHC13** [comment]
Thanks for the quick reply @bhauman . I tried that as well. Even that doesn't help.

**Comment by bhauman** [comment]
I have a high degree of confidence that adding :target to your figwheel coding changes the output directory and updates all the other internal paths.

**Comment by AkashHC13** [comment]
I'm not sure where I'm going wrong.
Here is what I have in my project.clj
```
(defproject app "0.1.0-SNAPSHOT"
  :plugins [[lein-cljsbuild "1.1.7"]
            [cider/cider-nrepl "0.21.1"]
            [refactor-nrepl "2.4.0"]
            [lein-pprint "1.2.0"]]
  :dependencies [[org.clojure/clojure "1.9.0"]
                 [org.clojure/clojurescript "1.10.520" :exclusions [commons-codec]]
                 ...
                 [com.bhauman/figwheel-main "0.2.0"]
                 [com.bhauman/rebel-readline-cljs "0.1.4"]]

  :source-paths ["src" "src-cljs"]
  :resource-paths ["target" "resources"]
  :clean-targets ^{:protect false} ["target/public"]
  
  :cljsbuild {:builds
              ...
              }
  :aliases {"fig" ["trampoline" "run" "-m" "figwheel.main"]}
  :profiles {:dev {:dependencies [[com.cemerick/piggieback "0.2.1"]
                                  [org.clojure/tools.nrepl "0.2.12"]]
                   :target "resources/public"
                   :repl-options {:nrepl-middleware [cemerick.piggieback/wrap-cljs-repl]}}})
```
Still I see figwheel compiling it to `target/public/cljs-out/`

**Comment by AkashHC13** [comment]
I tried adding it in the `mybuild.cljs.edn` file.
```
^{:watch-dirs ["src-cljs"]}
{ :source-paths ["src-cljs/app"]
 :target "resources/public/js"
 :main app.core}
```
Still no luck.

**Comment by AkashHC13** [comment]
I looked at the documentation [here](https://figwheel.org/docs/compile_config.html) for compiler options and added the following in my `app-dev.cljs.edn` file. 
```
{:source-paths ["src-cljs/app"]
 :output-to "resources/public/js/app.js"
 :output-dir "resources/public/js"
 :main app.core}
```
It worked. Thanks. Will close the PR.
