### ISSUE TITLE
Compiled Clojurescript contains incorrect paths to files 

### ISSUE THREAD

**Issue by sortofsleepy** [bhauman/figwheel-main#19]
👋 Hello!

Trying to get back into Clojurescript land after being away for awhile. To be fair, it's possible I've skipped a step somewhere but I think I might have found an issue with how Figwheel is compiling things. 

* I'm using `lein` and starting from a completely blank project using the template found [here](https://github.com/bhauman/figwheel-main-template) 
* I start up the process using `lein fig:build` 
* Navigating to localhost:9500 and I see a bunch of errors in the console. 

Looking further into it, I see in the generated javascript that some of the paths are incorrectly formatted, for example this line .

`document.write('<script src="cljs-out\dev/goog/deps.js"></script>');`

Is there a reason the output is like this? If I change `cljs-out\dev` to `cljs-out/dev` and correct the other incorrect paths that get generated, then things load correctly and I'm left with just warnings and I see the connected status on `localhost:9500`

Any help is appreciated!

**Comment by sortofsleepy** [comment]
ah - I figured out a workaround, just had to specify an asset path in dev.cljs.edn, not sure if that's the intended workflow?

**Comment by bhauman** [comment]
Are you on a windows machine?

**Comment by bhauman** [comment]
Thanks for the report!

**Comment by sortofsleepy** [comment]
@bhauman sorry! just saw this. Yea I am on a windows machine. 

Of course! Just doing my small small part. Thank you for putting out such an amazing tool! 🎉

**Comment by alzadude** [comment]
Hi @bhauman @sortofsleepy @webcoyote @kewne just to follow up on my previous comment, I did a little bit more investigation, by comparing the output from the ClojureScript compiler as used by Figwheel, with the output from the compiler when used directly (from the Clojure cli/deps.edn in my case).

In the output using Figwheel, the relevant lines look like this (with the backslashes that result in Figwheel being unable to work on Windows):
```
require(path.join(path.resolve("."),"target\node\dev","goog","bootstrap","nodejs.js"));
require(path.join(path.resolve("."),"target\node\dev","cljs_deps.js"));
```
Whereas in the output using the compiler directly, the relevant lines look like this:
```
require(path.join(path.resolve("."),"out","goog","bootstrap","nodejs.js"));
require(path.join(path.resolve("."),"out","cljs_deps.js"));
```
The `out` path above is the result of me specifiying `:output-to` `"out/<file>.js"` in the compiler options.

Perhaps this allows to narrow down the cause of the issue? I haven't been able to determine the reason why the above outputs are different yet (in terms of the path parsing/processing and where the backslashes are coming from!)

**Comment by writepavel** [comment]
I'm using the following workaround and it works on Windows machine:
added line `:asset-path "target//node//dev"`
into `test.cljs.edn` and `dev.cljs.edn` files
