### ISSUE TITLE
after-load hook is not work in version 0.2.1

### ISSUE THREAD

**Issue by DogLooksGood** [bhauman/figwheel-main#192]
People who looking for figwheel-main will find the version 0.2.1 from README. However in this version `:after-load` hook is not working. Switching to 0.2.0 or 0.2.1-SNAPSHOT will solve the problem.

**Comment by bhauman** [comment]
Yes your right! Thanks for the report will try to have it fixed by tomorrow.

**Comment by bhauman** [comment]
I just released 0.2.2-SNAPSHOT which fixes this.
