### ISSUE TITLE
:figwheel-no-load is not honored

### ISSUE THREAD

**Issue by antonmos** [bhauman/figwheel-main#194]
app.cljs:
```
(ns ^:figwheel-no-load my.app
  )

(enable-console-print!)
(println "test one two")
```

I tested the following:
if i change any cljs file, i do NOT "test one two" printed in the console
if I change the app.cljs file, i DO see  "test one two" printed in the console

The above make sense, but somehow, periodically, i see that app.cljs does get reloaded when no changes have been made to app.cljs

**Comment by bhauman** [comment]
Try 0.2.2-SNAPSHOT

**Comment by antonmos** [comment]
it hasnt happened since i started using the snapshot!

**Comment by antonmos** [comment]
Thanks for fixing so quickly! btw, it seems that 2.3.0 has been published but not pushed to master.
