### ISSUE TITLE
"Your own server" - figwheel does not start

### ISSUE THREAD

**Issue by keithmantell** [bhauman/figwheel-main#213]
If I issue 
`clojure -i scripts/server.clj -m figwheel.main -b dev -r`

The jetty server starts but I see no evidence that figwheel has started.

**Comment by keithmantell** [comment]
[deps.edn.txt](https://github.com/bhauman/figwheel-main/files/3718766/deps.edn.txt)
[index.html.txt](https://github.com/bhauman/figwheel-main/files/3718774/index.html.txt)

**Comment by zengxinhui** [comment]
Is this the same as reported earlier [here:](https://github.com/bhauman/figwheel-main/issues/169)?
Figwheel-main bug perhaps?

**Comment by keithmantell** [comment]
I would say yes, it is

**Comment by zengxinhui** [comment]
I figure it out. The problem is that (run-jetty) is blocking. Changing the join? will help.

(run-jetty
 (wrap-defaults handler site-defaults)
 {:port 4000
  **:join? false**})
