### ISSUE TITLE
Minimal template not working

### ISSUE THREAD

**Issue by Kurren123** [bhauman/figwheel-main#22]
OS: Windows 10.

I'm completely new to Clojure. I run
 
```
lein new figwheel-main hello-world.app -- --reagent
cd .\hello-world.app\
lein fig:build
```

The project compiles successfully and opens the browser, but I get a blank page. I inspect HTML body and get

```
<body>
    <div id="app">
    </div>
    <!-- end of app div -->
    <script src="cljs-out/dev-main.js" type="text/javascript"></script>
    <script src="cljs-outdev/goog/base.js"></script>
    <script src="cljs-outdev/goog/deps.js"></script>
    <script src="cljs-outdev/cljs_deps.js"></script>
  ...
</body>
```

However there is no folder called `cljs-outdev/`, I'm guessing those paths should be `cljs-out/dev/`?

Thanks

**Comment by bhauman** [comment]
I recently fixed this problem but haven't deployed it.  

Please try changing the generated project.clj to point to `[com.bhauman/figwheel-main "0.1.5-SNAPSHOT"]`

make sure you do a `lein clean` and then try `lein fig:build`

**Comment by Kurren123** [comment]
@bhauman Thank you for your help. It compiles now but the reloading doesnt work. Specifically I change `(defonce app-state (atom {:text "Hello world!"}))` to `(defonce app-state (atom {:text "Hello world! 123"}))` and nothing happens in the browser (Chrome)
