### ISSUE TITLE
doc macro doesn't work initially with headless browser

### ISSUE THREAD

**Issue by pyrmont** [bhauman/figwheel-main#224]
**Summary**

When Figwheel is launched with the initial evaluation environment being a headless browser, the `doc` macro does not work.

**Steps to Reproduce**

1. Disable launching in a browser, either by setting `:open-url` to `false` or by setting `:launch-js` to launch a headless browser.
2. If `:open-url` was set to `false`, connect to Figwheel with the headless browser.
3. Type `(doc +)`.

**Expected Result**

```
-------------------------
cljs.core/+
([] [x] [x y] [x y & more])
  Returns the sum of nums. (+) returns 0.
```

**Actual Result**

```
#object[TypeError TypeError: Cannot read property 'print_doc' of undefined]
         (<NO_SOURCE_FILE>)
```

**Additional Notes**

- If the headless browser is run from a separate terminal, then in the JavaScript REPL for the headless browser you can type `cljs`. This will produce the following output:
  
  ```
  {"result":{"className":"Object","description":"Object","objectId":"{\"injectedScriptId\":2,\"id\":1}","type":"object"}}
  ```
  Once this happens, if you switch back to the Figwheel REPL, the `doc` macro will now work.

- The `print_doc` function is the compiled JavaScript version of the `cljs.repl/print-doc` function  ([definition](https://github.com/clojure/clojurescript/blob/9a8196ebfe4265feda88a06de84affb9df469012/src/main/cljs/cljs/repl.cljs#L13-L56)). It is called by the `doc` macro ([definition](https://github.com/clojure/clojurescript/blob/9a8196ebfe4265feda88a06de84affb9df469012/src/main/clojure/cljs/repl.cljc#L1233-L1267)).

- The `source` macro ([definition](https://github.com/clojure/clojurescript/blob/9a8196ebfe4265feda88a06de84affb9df469012/src/main/clojure/cljs/repl.cljc#L1328-L1335)) always works.

**Comment by pyrmont** [comment]
This appears to be a consequence of running the headless browser in REPL mode (i.e. `--repl`). If I run `chromium --headless --disable-gpu --remote-debugging-port=9222 --no-sandbox`, the above problems don't manifest. Apologies for the trouble.

**Comment by tankorsmash** [comment]
I'm running into a similar issue, although not headless at all (`../elsewhere/lein.bat fig -- -b dev --repl`) and also see "Cannot read property 'print_doc' of undefined" when trying to call `doc` on anything.

How did you manage to track this down @pyrmont, maybe I can do the same steps on my machine to try and nail it down.

**Comment by pyrmont** [comment]
@tankorsmash I'm sorry, I don't remember what I did at this point. Best of luck tracking things down.
