### ISSUE TITLE
Figwheel-main broken with expound 0.8.+

### ISSUE THREAD

**Issue by Whoops** [bhauman/figwheel-main#227]
Expound removed the `with-color-when` macro in version 0.8.0. This causes Figwheel to fail with the error:
```
Syntax error compiling at (figwheel/main.cljc:211:10).
No such var: expound.ansi/with-color-when
```
When using newer versions of expound.

**Comment by bhauman** [comment]
This is deployed to 0.2.4-SNAPSHOT
