### ISSUE TITLE
weird java compilation error when using :target :bundle

### ISSUE THREAD

**Issue by gdanov** [bhauman/figwheel-main#247]
Hi,
 I have working project that targets browser. Due to one dependency that's not properly bundled (has `require()` in it) I decided to give the new :bundle target a go.
 Problem is, once I switch the target, I get the exception bellow very early in the start. I have disabled all the custom parts of the build I have, but still same exception. 

```
[Figwheel] Compiling build dev to "target/public/cljs-out/dev-main.js"
[Figwheel] Failed to compile build dev in 0.206 seconds.
[Figwheel:WARNING] Compile Exception: contains? not supported on type: java.lang.Boolean
[Figwheel:SEVERE] java.lang.IllegalArgumentException: contains? not supported on type: java.lang.Boolean
```

here is the config as seen by figwheel:

```
[Figwheel:FINEST] Verbose config: {:figwheel.main/build
 {:id "dev",
  :config
  {:open-url false,
   :watch-dirs ["src/shared" "src/front"],
   :log-level :all,
   :ring-handler handler/handler}},
 :ns experiment.core,
 :figwheel.main/join-server? false,
 :figwheel.main/post-build-hooks
 (#function[figwheel.main/config-cljsc-opts-json/fn--7922]),
 :figwheel.main/initializers
 [#function[figwheel.main/config-figwheel-mode?/fn--7719]
  #function[figwheel.main/config-system-exit/fn--7830]],
 :repl-env-options
 {:ring-handler #'handler/handler,
  :open-url false,
  :connection-filter
  #function[figwheel.main/config-repl-connect/fn--7791],
  :output-to "target/public/cljs-out/dev-main.js",
  :output-dir "target/public/cljs-out/dev",
  :target :bundle,
  :ring-stack-options
  #:figwheel.server.ring{:dev
                         #:figwheel.server.ring{:system-app-handler
                                                #function[figwheel.main/add-default-system-app-handler/fn--8067/fn--8068]}}},
 :figwheel.main/config
 {:mode :repl,
  :open-url false,
  :watch-dirs ("src/shared" "src/front"),
  :log-level :all,
  :ring-handler #'handler/handler,
  :figwheel.main/build-inputs ["src/shared" "src/front"]},
 :options
 {:output-dir "target/public/cljs-out/dev",
  :closure-defines
  #:figwheel.repl{connect-url
                  "ws://localhost:9500/figwheel-connect?fwprocess=4e9b4f&fwbuild=dev"},
  :install-deps true,
  :optimizations :none,
  :aot-cache false,
  :preloads
  [example.procstub
   example.devcardsentry
   figwheel.core
   figwheel.main
   figwheel.repl.preload
   devtools.preload
   figwheel.main.system-exit],
  :figwheel true,
  :output-to "target/public/cljs-out/dev-main.js",
  :asset-path "/cljs-out/dev",
  :bundle-cmd
  {:none ["npx" "webpack" "--mode=development"],
   :default ["npx" "webpack"]},
  :repl-requires
  ([figwheel.repl :refer-macros [conns focus]]
   [figwheel.main
    :refer-macros
    [stop-builds start-builds build-once reset clean status]]
   [cljs.pprint :refer [pprint] :refer-macros [pp]]
   [cljs.repl :refer-macros [source doc find-doc apropos dir pst]]),
  :target :bundle,
  :devcards true,
  :main experiment.core,
  :npm-deps
  {"react-reconciler" "0.25.1",
   "react" "16.9.0",
   "react-dom" "16.9.0",
   "paper" "0.12.4"}},
 :repl-options
 {:output-dir "target/public/cljs-out/dev",
  :closure-defines
  #:figwheel.repl{connect-url
                  "ws://localhost:9500/figwheel-connect?fwprocess=4e9b4f&fwbuild=dev"},
  :inits [{:type :init-forms, :forms nil}],
  :install-deps true,
  :optimizations :none,
  :aot-cache false,
  :preloads
  [example.procstub
   example.devcardsentry
   figwheel.core
   figwheel.main
   figwheel.repl.preload
   devtools.preload
   figwheel.main.system-exit],
  :figwheel true,
  :output-to "target/public/cljs-out/dev-main.js",
  :asset-path "/cljs-out/dev",
  :bundle-cmd
  {:none ["npx" "webpack" "--mode=development"],
   :default ["npx" "webpack"]},
  :repl-requires
  ([figwheel.repl :refer-macros [conns focus]]
   [figwheel.main
    :refer-macros
    [stop-builds start-builds build-once reset clean status]]
   [cljs.pprint :refer [pprint] :refer-macros [pp]]
   [cljs.repl :refer-macros [source doc find-doc apropos dir pst]]),
  :analyze-path ["src/shared" "src/front"],
  :target :bundle,
  :devcards true,
  :npm-deps
  {"react-reconciler" "0.25.1",
   "react" "16.9.0",
   "react-dom" "16.9.0",
   "paper" "0.12.4"}}}
```

**Comment by bhauman** [comment]
hmmm is there any way that you can get me a stacktrace?

A couple of trouble shooting tips.

Also, there is a different subtle problem, your `:output-to` needs to be in the `:output-dir` directory so that the bundle can bundle it.  In your case it should be "target/public/cljs-out/dev/main.js".  I'm currently writing this up in the docs.  I'll also push out the latest SNAPSHOT.

But I could really use that stacktrace.

**Comment by bhauman** [comment]
You can also troubleshoot by removing `:bundle-cmd` running `webpack` from the command line to see if the compile completes and to check that `npx webpack` is working

**Comment by gdanov** [comment]
Thanks for the prompt reply. My debugging shows that [this is where the exception is being fired](https://github.com/clojure/clojurescript/blob/master/src/main/clojure/cljs/closure.clj#L2380)

the output folder is not a problem yet, I'm not getting there. I tried removing the bundle command, changes nothing. I'll spend some time now trying to figure out why cljs is getting structure it does not seem to be expecting

**Comment by bhauman** [comment]
OK so that is in the CLJS compiler and it refers to how you are requiring an NPM library I think. 

So I'd look for the offensive require and then file a report or ask on slack on cljs-dev

**Comment by gdanov** [comment]
> OK so that is in the CLJS compiler and it refers to how you are requiring an NPM library I think.
> 
> So I'd look for the offensive require and then file a report or ask on slack on cljs-dev

require in what part of the code/config?

**Comment by bhauman** [comment]
So it's not Figwheel that's causing this error. Which is good to hear :)

**Comment by bhauman** [comment]
Its somewhere in an ns where you use (:require [react]) to include an NPM library.

**Comment by bhauman** [comment]
You could just make a tiny cljs.main project and try to require each of the npm libraries you need. This will be helpful to learn what the pattern is.

**Comment by bhauman** [comment]
Wait, I see something. I see you're using :npm-deps that might be it. It may have something to do with figwheel. Hold on.

**Comment by bhauman** [comment]
Remove the `:install-deps` key.  Also I'm worried that `:npm-deps` is getting set to false. It shouldn't be.

**Comment by bhauman** [comment]
It's probably best to use npm and your package.json directly

**Comment by bhauman** [comment]
Yes I think that is it.

**Comment by gdanov** [comment]
pls have a look at the variable values, maybe that helps. It's the same call, two different places in the call stack.

<img width="1176" alt="Screenshot 2020-05-26 at 17 30 11" src="https://user-images.githubusercontent.com/957113/82919899-e7ac2f80-9f76-11ea-8b55-a517f659e3f8.png">
<img width="540" alt="Screenshot 2020-05-26 at 17 32 14" src="https://user-images.githubusercontent.com/957113/82919907-eb3fb680-9f76-11ea-874a-47abe5e42f5b.png">

**Comment by bhauman** [comment]
yes I see, what were the opts before they went through (add-implicit-opts opts)

**Comment by gdanov** [comment]
I believe this is where the perfectly valid :npm-deps are replaced with `true`


<img width="486" alt="Screenshot 2020-05-26 at 17 36 21" src="https://user-images.githubusercontent.com/957113/82920464-97819d00-9f77-11ea-828f-dfc21e70ab63.png">

**Comment by bhauman** [comment]
https://github.com/clojure/clojurescript/blob/master/src/main/clojure/cljs/closure.clj#L2508
yep just found it myself

:npm-deps doesn't work with :bundle target

**Comment by bhauman** [comment]
We should warn for that shit :)

**Comment by bhauman** [comment]
I think that's this is because `:npm-deps true` causes a scan of the node modules. It's not really a declaration of dependencies.

**Comment by bhauman** [comment]
I'm about to release 0.2.6 and along with some docs on how to use the new Bundle feature.
I'm on Slack now BTW if you need more help with this.

**Comment by gdanov** [comment]
First, thanks for the `:output-to` hint. I got the thing running.

I read the article announcing :target :bundle and imagined it's some sort of next level npm integration, so kinda expected to get better UX for :npm-deps. Frankly, the consumption of npm modules by clojurescript has been pain in the butt since day one, and even though I got fairly proficient with the JS ecosystem by doing JS fullstack work for a while, it's still often very confusing to know what combination of options works in which context (fully aware that's in cljs's yard) so I'd love to see figwheel-main as one-stop-shop where I can start web project with minimal overture.

> I'm about to release 0.2.6 and along with some docs on how to use the new Bundle feature.
> I'm on Slack now BTW if you need more help with this.

thanks a lot for the support! I normally try to stay away from slack

**Comment by bhauman** [comment]
https://github.com/clojure/clojurescript/commit/57941cf07d6745e79d04410538d8d19bbb86a7f8

**Comment by bhauman** [comment]
Apparently there is another bug around this in CLJS, so thanks for helping find it. It seems that what you specified should have worked.

**Comment by bhauman** [comment]
clojurescript 1.10.773 fixes your issues

**Comment by gdanov** [comment]
Thanks, tested it (incl. several permutations I typically try when things are broken) and everything works as expected. Fells very luxurious :)

I spent little time thinking and what surprises me is that I hit this bug first. This shows I'm using set-up that's not common and that's pretty big surprise (to me). I try not to be early adopter of build tools. Couple thoughts that may be useful, in random order:

* coming from react-scripts, first I'm used to consume npm modules, second all the processing involved is smoothly working black box. I expected figwheel to give me similar experience (which it does now with :target :bundle)
  * I hit this bug due to npm module of a browser lib that's not proper web bundle (has require() in the minimized version). This broke the build so I remembered I read recently about :target :build. I must've been lucky with the npm deps I used before this not to hit similar case
* if my use of npm-modules for web dev is fairly exotic, what's the default then? In the (excellent) figwheel-main tutorial consuming other modules (npm or not) is not discussed

I'd put some tutorial how to do this already to help the community if I felt confident I know what I'm doing but this is not how I feel yet. Btw [this](https://www.reddit.com/r/Clojure/comments/8pczq5/a_long_journey_exploring_npmdeps_and_clojurescript/) is indicative of the dev ex. Once again — not ranting or complaining. 

P.S. not to come across as rude rejecting to talk on slack — I prefer tickets to slack because they are indexed so someone with my problem would find solution easier. For this (and pretty much any serious work) slack is broken (to me).

**Comment by bhauman** [comment]
@gdanov I think most if this chalks up to the fact that the `:bundle` target is bleeding edge right now.  Very few people are using it yet.  Those were really bad bugs and they shouldn't have been in there.  I'm trying to document this stuff here https://figwheel.org/docs/npm.html

NPM integration is going down a better path now and I'm hoping these problems will be a thing of the past.
