### ISSUE TITLE
Docs for using NPMs

### ISSUE THREAD

**Issue by jkdufair** [bhauman/figwheel-main#267]
Fairly new to figwheel. Ran into a couple of things that may be helpful for the documentation?

- As seen in #266, the current docs (at the very least `:auto-bundle :webpack`) only work with webpack 4. Not sure why webpack 5 requires specifying paths prefixed with `./`
- It took me a while to figure out I needed to updated my `index.html` to point to the webpack bundle. The docs mention updating `index.html` but I only read them to mean that one should do so in certain cases that didn't apply to the basic instructions (i.e. basic npm init, add package via npm, auto-bundle). Maybe this could be included. And/or maybe modifying the docs is not necessary and I'm still doing something wrong?

**Comment by jkdufair** [comment]
My apologies. I didn’t see that the docs are in the repo. I’ll submit a PR.

**Comment by bhauman** [comment]
This is fixed in 0.2.12-SNAPSHOT

**Comment by jkdufair** [comment]
Thank you!
