### ISSUE TITLE
CSS Reloading on every clients

### ISSUE THREAD

**Issue by lyderichti59** [bhauman/figwheel-main#269]
Hi,

I have noticed that when I launch Figwheel in REPL mode, and connect several clients to it, CSS reloading works for :
-> the only client on which the focus is (if :broadcast is set to false)
-> every clients (if :broadcast is set to true)

Thus, if I want to do CSS reloading for everyone, I must enable broadcasting but I am then targetting every clients with the REPL.

Is it the desired behaviour ?

I just thought that maybe there should be another broadcast flag for css reloading, or at least a documented section on this, with workarounds for example.

**Comment by bhauman** [comment]
This is a good point. I made it broadcast CSS changes. 

I'm deploying this to 0.2.13-SNAPSHOT
