### ISSUE TITLE
issues with clojurescript 1.10.844

### ISSUE THREAD

**Issue by henryw374** [bhauman/figwheel-main#287]
Figwheel reports some errors when using 1.10.844. 

description of breaking changes:

https://github.com/clojure/clojurescript-site/blob/0d35426cbb18521ece37f6e7c16b108a9883935c/content/news/2021-04-xx-release.adoc#noteworthy--breaking-changes

**Comment by bhauman** [comment]
Thanks! Looking at this now.

**Comment by bhauman** [comment]
Just deployed the fixes to 0.2.13

**Comment by henryw374** [comment]
Awesome. I've got the new snapshot and see no errors now - everything working fine, cheers!
