### ISSUE TITLE
Add support for nREPL 0.4+

### ISSUE THREAD

**Issue by bbatsov** [bhauman/figwheel-main#29]
Just a continuation of https://github.com/nrepl/piggieback/pull/92

Looking at the code it seems you'll only have to make one change here https://github.com/bhauman/figwheel-main/blob/cc141a35a9cbcd016a70e5e4753825a0a959ea37/src/figwheel/main.cljc#L1230

**Comment by bhauman** [comment]
fixed

**Comment by bbatsov** [comment]
Thanks!
