### ISSUE TITLE
logger set-up exception at browser start-up

### ISSUE THREAD

**Issue by gdanov** [bhauman/figwheel-main#297]
I'm using latest figwheel-main release with clojurescript excluded in the deps.
When I switch from cljs 1.10.866 to git commit ` :sha "9027c02852bbeb512cda728e5f0551145e921a9c"` I get the exception below in the browser upon first page load.

I'm using that specific cljs commit because I'm testing the fix in it.

```
Uncaught TypeError: logger_SINGLEQUOTE_.setLevel is not a function
    at figwheel$repl$logging$set_log_level (logging.cljs:63)
    at figwheel$repl$init_log_level_BANG_ (repl.cljc:601)
    at figwheel$repl$connect_STAR_ (repl.cljc:604)
    at repl.cljc:613
    at Function.cljs$core$IFn$_invoke$arity$variadic (repl.cljc:613)
    at figwheel$repl$connect (repl.cljc:611)
    at preload.cljs:5
figwheel$repl$logging$set_log_level @ logging.cljs:63
figwheel$repl$init_log_level_BANG_ @ repl.cljc:601
figwheel$repl$connect_STAR_ @ repl.cljc:604
(anonymous) @ repl.cljc:613
(anonymous) @ repl.cljc:613
figwheel$repl$connect @ repl.cljc:611
(anonymous) @ preload.cljs:5
load (async)
(anonymous) @ preload.cljs:5
```

**Comment by jleonard-r7** [comment]
I'm also seeing this.

**Comment by athomasoriginal** [comment]
Running into a similar situation.  This is a screen cap from Safari, but the issue exists in general:

<img width="1325" alt="Screen Shot 2021-11-04 at 7 56 02 PM" src="https://user-images.githubusercontent.com/8523922/140436284-7097ee6e-13ab-4eec-8d52-e08343a0c21e.png">

**Comment by henryw374** [comment]
based on this demo, https://github.com/google/closure-library/blob/master/closure/goog/demos/debug.html it looks like goog.log is what it should be moved to

**Comment by bhauman** [comment]
So there were breaking changes in the goog.log library introduced in recent versions of the google closure compiler which translates to breaking changes in clojurescript.  So if you roll the clojurescript version back you unfortunately need to roll figwheel back as well which is a pain I realize. The other solution would be to abstract log calls and detect which api is in use on loading. There have been several different breaking changes to logging over the last few years.

**Comment by henryw374** [comment]
With the current versions of figwheel and clojurescript I see a bunch of logging errors  - which stops figwheel working. It may not be exactly the issue as was raised here but obviously related

**Comment by bhauman** [comment]
Yep that checks out. Man I should never have used google closures logging system. They change it way too often, I'm going to just strip it out that way there are no backwards compatibility problems. But for now I'm going to fix the current problem.

**Comment by bhauman** [comment]
Alrighty, I just deployed 0.2.15-SNAPSHOT and it should address all of the above issues.

Let me know if it is working for you.

Be sure to clean your compiled cljs files before checking testing it :)

Thanks all!

**Comment by henryw374** [comment]
thanks. still seeing error thrown from https://github.com/bhauman/figwheel-core/blob/master/src/figwheel/core.cljc#L112 

looks like name cannot be nil

**Comment by athomasoriginal** [comment]
Just a little more context: 0.2.15-SNAPSHOT + CLJS 1.10.891

<img width="863" alt="Screen Shot 2021-11-10 at 9 42 06 AM" src="https://user-images.githubusercontent.com/8523922/141133768-f2b738e4-efd5-4341-945f-7c4d6d7a3a7c.png">

**Comment by bhauman** [comment]
thanks! I guess my last commit didn't make it into the release

**Comment by bhauman** [comment]
Just re-deployed the SNAPSHOT. Sorry for the lost cycles.

**Comment by athomasoriginal** [comment]
Did it make it out?  I deleted my `~/.m2` of `0.2.15-SNAPSHOT` to be sure and still seeing similar issues. 🤔

**Comment by bhauman** [comment]
Really I'm using it locally just fine

**Comment by bhauman** [comment]
did you clean your compiled artifacts?

**Comment by athomasoriginal** [comment]
At this point, I've also deleted everything in the target dir and cleared cache/hard refreshed browsers (all 3 + using incognito).  The `nm` error is gone now (win!), but the browser console errors I get are:

**Chrome**

<img width="1195" alt="Screen Shot 2021-11-10 at 8 00 02 PM" src="https://user-images.githubusercontent.com/8523922/141217995-48c16329-a2b3-4937-af6b-e54384a013e7.png">

**Firefox**

<img width="1274" alt="Screen Shot 2021-11-10 at 8 00 47 PM" src="https://user-images.githubusercontent.com/8523922/141218056-788e8311-49c9-4c18-ab1e-bd938072c90b.png">


<img width="1274" alt="Screen Shot 2021-11-10 at 8 01 16 PM" src="https://user-images.githubusercontent.com/8523922/141218106-db17ee65-d959-433a-b367-c8b51460787f.png">

**Comment by bhauman** [comment]
This is very strange. These to look like the Javascript errors that would result from the missing 'nm' error.

**Comment by bhauman** [comment]
Do you have :aot-cache set to true?

**Comment by bhauman** [comment]
I just deleted my .m2 as well and launched a project generated by the figwheel-main-template and it all seems to work with the jars pulled down from clojars.

**Comment by henryw374** [comment]
latest snapshot working for me. Thanks!

**Comment by athomasoriginal** [comment]
Works, Bruce!! Thanks again and apologies for the gas lighting!  What worked for me:

- deleted all the `.m2`'s in main, core and real
- deleted `target` compiled artifacts
- restarted services

Appreciate you ❤️

**Comment by bhauman** [comment]
just deployed 0.2.15 with these fixes
