### ISSUE TITLE
add support for clojure's new as-alias functionality

### ISSUE THREAD

**Issue by drewverlee** [bhauman/figwheel-main#318]
Figwheel 0.2.16 is issuing a warning about a new addition to the clojure require macro [:as-alias](https://clojure.org/news/2022/03/22/clojure-1-11-0)

```
[Figwheel] Failed to compile build dev in 0.168 seconds.
[Figwheel:WARNING] Could not Analyze: Only :as, :refer and :rename options supported in :require / :require-macros; offending spec: [some.ns :as-alias news-app] at line.... 
````

the ns in question

```
(ns some.ns
  (:require
   [some.ns :as-alias news-app]]))
```

It probably shouldn't. 

(side note: would this cause my build to fail?)

**Comment by timothypratley** [comment]
Hi @drewverlee :wave: 

This is a ClojureScript bug (not Figwheel) and should be reported upstream, see: https://clojurescript.org/community/reporting-issues. Thank you for discovering it!

**Comment by bhauman** [comment]
Going to close this.
