### ISSUE TITLE
see if an :asset-path that starts at the root will work i.e "/cljs-out/dev"

### ISSUE THREAD

**Issue by bhauman** [bhauman/figwheel-main#35]
i.e "/cljs-out/dev" instead of "cljs-out/dev"

This will help folks who are using html pushstate navigation

**Comment by danielcompton** [comment]
This makes things a little more complicated if you are hosting your CLJS app on a subdirectory (i.e. using nginx to proxy it along with the rest of your app). The previous default asset path of `cljs-out/dev` worked for serving your HTML from any depth of subdirectory. Now, you need to manually add the relative path back in for it to be resolved correctly.

I'm mostly leaving this comment as a signpost to myself and future searchers who may wonder about how to set this up correctly. Not sure if you'd want to reconsider this behaviour, I don't know how this improves things for people using html pushstate?

**Comment by bhauman** [comment]
It helps folks with pushState because the relative loading that occurs on page reload of a non root url will break fail.  This is definitely a case of having to optimize for the most common use case. Relative loading will break in any case where the loading url changes.  i.e. "localhost:3000/" -> "localhost:3000/admin" which is common in both pushstate navigation and just plain Rails/Django like http applications.  Relative load requires the SPA URL stays absolutely stable.
