### ISSUE TITLE
Fail gracefully when `browse` fails to open a browser

### ISSUE THREAD

**Issue by ryrobes** [bhauman/figwheel-main#47]
Could we make the browser launch step fail gracefully or be skippable via a cli parameter? This is especially an issue on windows (via WSL) or on a headless VM it will always crash at "Opening URL" unless you have a proper x-windows set up.  

If an option exists and I missed it, forgive me.

clojure -Sdeps "{:deps {com.bhauman/figwheel-main {:mvn/version \"0.1.5\"} com.bhauman/rebel-readline-cljs {:mvn/version \"0.1.4\"}}}}"  -m figwheel.main

"Opening URL http://localhost:9500
Exception in thread "main" java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)" 

Making it work well on WSL might make more sense than creating a slightly forked "Windows version" (I'm using the CLI on WSL also, which works fine even though they have not released "native" windows CLI versions....).

**Comment by bhauman** [comment]
`:open-url false`

**Comment by bhauman** [comment]
Failing gracefully here makes sense though

**Comment by bhauman** [comment]
This has been fixed in recent commits to https://github.com/bhauman/figwheel-repl

**Comment by bhauman** [comment]
https://github.com/bhauman/figwheel-repl/commit/8b2823b9c667c7543dd2dfd4dd074f8c73bc3fa0
