### ISSUE TITLE
Single segment namespaces in clj files fail to reload.

### ISSUE THREAD

**Issue by thiru** [bhauman/figwheel-main#48]
With the setup I have [here using rebel-readline + clojure cli + deps.edn (no Leiningen)](https://github.com/thiru/fullstack-clojure/tree/rebel) figwheel isn't able to compile `.clj` files.

Steps to reproduce:
`$ clojure -A:rebel`
```clojure
user=> (fig/start {:mode :serve} "dev")
user=> (fig/cljs-repl "dev"))
```
Modify `src/user.clj` and save.
Note the error:

```clojure
cljs.user=> [Figwheel] Could not Analyze   /.../fullstack/src/user.clj   line:1  column:1

  Don't know how to create ISeq from: clojure.lang.Keyword

  1  (ns user
     ^---
  2    (:require [figwheel.main :as fig]
  3              [fullstack.helpers :refer :all]))
  4
  5  (def x {:a 1})
  6

[Figwheel:SEVERE] java.lang.IllegalArgumentException: Don't know how to create ISeq from: clojure.lang.Keyword
```

**Comment by bhauman** [comment]
I have done significant refactor and deployed it to `0.1.6-SNAPSHOT`. I didn't see this behavior when I used it.

**Comment by thiru** [comment]
Hmm just tried with the latest but still getting the error.  I even tried using the :gir/url method in deps.edn to target the latest hash.  Also tried without using rebel-readline.. so just running `clj`.

It happens right after calling `user=> (fig/start {:mode :serve} "dev")`.

I'm using OpenJDK 10 if that makes any difference.  Though it works when I use Leiningen..

**Comment by bhauman** [comment]
OK I found the problem, this is only a problem with single segment namespaces.

**Comment by bhauman** [comment]
This is a problem with using ana/parse-ns in figwheel.core/clj-paths->namespaces

**Comment by bhauman** [comment]
Fixed here:
https://github.com/bhauman/figwheel-core/commit/57f6171d608e522bd5a8b171b51b0d9254a00f52

**Comment by bhauman** [comment]
also addressed here: https://github.com/bhauman/figwheel-main/commit/d43d6bafc024cc88bd8a7c7cc6bfab39a5fad039
