### ISSUE TITLE
problems with extra-mains

### ISSUE THREAD

**Issue by henryw374** [bhauman/figwheel-main#64]
Hi, 

I really like the idea of this but I've got a couple of issues:

1) how to repl in to a particular main? The scripting-api repl fn takes just build-id as an arg, but all these are in the same build. 

2) I'm trying to use :after-load metadata to replace on-jsload. This would reload the react app in the app build and re-run the tests in the test build, but it seems like only one of the after-load fns gets used. I see a message in the other app that it has been unable to find the other reload fn (and I'd expect it not to be there).

I've tried to work around these problems by using multiple builds, started via scripting api, but am actually hitting issue 2 there as well.

If you need any more info please let me know. 

Thanks,
Henry

**Comment by bhauman** [comment]
You can change the focus of your cljs-repl, by looking at the
`figwheel.repl/conns` and the using `figwheel.repl/focus` to switch to a
different browser tab.

As for the re-loads I will have to check that out and see what the problem
is.

**Comment by henryw374** [comment]
awesome, thanks!

**Comment by bhauman** [comment]
you switch repl context from inside the cljs-repl

**Comment by bhauman** [comment]
Oh and that warning about the hook missing is expected for now, even if its a bit confusing.

**Comment by henryw374** [comment]
yes I know ...  but within the repl I don't get a helpful error message (guess because it's a macro), so I was trying to dig down a bit to see what might be the issue. and I think it is that possibly the code is expecting the cljs.repl env to be bound and it's not?

thanks for info on the hook, I guess using one hook fn that will try to do many things, swallowing errors if they don't work in that env

**Comment by bhauman** [comment]
are you using the latest figwheel.main 1.8.0?

**Comment by henryw374** [comment]
0.1.8 yes

**Comment by bhauman** [comment]
OK and you are saying that when you have to windows open for both mains, and then you call `(figwheel.repl/conns)` from the cljs.repl prompt? You get an error?

**Comment by henryw374** [comment]
yes

**Comment by bhauman** [comment]
and what is that error?

**Comment by bhauman** [comment]
and are you using nREPL?

**Comment by henryw374** [comment]
yes nrepl. it's something like 'can't evaluate ..' the sort of problem-with-a-macro kind of error.

**Comment by henryw374** [comment]
fyi, i tried require'ing figwheel.repl just to be sure it's there and it is. and the conns macro is there

**Comment by bhauman** [comment]
did you try to call it explicitly with the namespace `(figwheel.repl/conns)`?

**Comment by bhauman** [comment]
ohhh, you need the latest piggieback

**Comment by bhauman** [comment]
0.3.9

**Comment by henryw374** [comment]
ok cool. will give that a go now

**Comment by bhauman** [comment]
I had to do a bunch of work on it to get things to work right

**Comment by henryw374** [comment]
I can imagine it's fiddly. Ok all good now, thanks
