### ISSUE TITLE
:import decl in main.cljc doesn't compile against new core specs

### ISSUE THREAD

**Issue by lgrapenthin** [bhauman/figwheel-main#70]
Apparently writing (:import [my.class]) is not working anymore. One is supposed to either write (:import [my class]) or (:import my.class) or nothing in case one doesn't need aliases.

**Comment by bhauman** [comment]
what version of Clojure is causing this? I'm assuming 1.10 something?

**Comment by bhauman** [comment]
I'll make my tests run with that version as well

**Comment by lgrapenthin** [comment]
core.specs.alpha 0.2.44
Included in the newly released 1.10.0-alpha7

**Comment by bhauman** [comment]
thanks!

**Comment by bhauman** [comment]
fixed and just deployed to 0.1.9-SNAPSHOT
