### ISSUE TITLE
Host and port cannot be set on Node's --inspect

### ISSUE THREAD

**Issue by adambubenicek** [bhauman/figwheel-main#72]
It would be nice if the `:inspect-node` option also accepted a map of `:host` and `:port`, to be on par with Node's `--inspect=[[host:]port]` flag format.

Currently, if user wants to remap those, a separate shell script (running node with the correct flag) needs to be created, its path passed to `:node-command` *and* `:inspect-node` set to `false` to prevent the flag from being passed twice.

One use case for a custom host is running from Docker, which doesn't properly route traffic from `127.0.0.1` host (which is the default for `--inspect`), as opposed to `0.0.0.0`.

If it makes sense, I can try to come up with an implementation. Thanks!

**Comment by bhauman** [comment]
See the `:launch-js` config option as it allows you to pass arbitrary args to start a process.
https://figwheel.org/config-options#launch-js

**Comment by adambubenicek** [comment]
Oh, I missed that, thank you!
