### ISSUE TITLE
Exception under some circumstances launching lein fig:build on windows 10

### ISSUE THREAD

**Issue by ingesolvoll** [bhauman/figwheel-main#74]
As reported on slack, my figwheel-main is highly dependent on folder name/structure and number of dependencies to be able to load. 

The project tested is the leiningen template as of yesterday.

I tested with the exact same project folder with different names and on different disk locations, with different but predictable results for each combination. Here are my findings:

Base folder is `c:/dev/go/src/backup-cse`

- The folder `/p012345678901234567890` works.

- The folder `p01234567890123456789` gives the exception `clojure.lang.ExceptionInfo: Figwheel: Unable to dynamicly load figwheel.server.jetty-websocket/run-server {:not-loaded figwheel.server.jetty-websocket/run-server}`

- The folder `p0123456789012345678901234567890123456789` gives the exception `java.lang.ClassNotFoundException: org.apache.commons.codec.binary.Base64, compiling:(ring/util/codec.clj:1:1)`

- Moving previous folder `p0123456789012345678901234567890123456789` to root (c:\) gives this exception `clojure.lang.ExceptionInfo: Figwheel: Unable to dynamicly load figwheel.server.jetty-websocket/run-server {:not-loaded figwheel.server.jetty-websocket/run-server}`

Also, adding or removing dependencies from the working project (first example) renders same exception as the second example.

**Comment by ingesolvoll** [comment]
Tested using Java 1.8.1_181 64 bit server VM, leiningen 2.8.1, OS Windows 10 Enterprise

**Comment by bhauman** [comment]
So this is a limitation of the OS and leiningen https://github.com/technomancy/leiningen/issues/2452

I'm going to close this, I do think that this begs for a solution, but it is outside of the scope of figwheel-main.
