### ISSUE TITLE
ClassNotFoundException figwheel.main.api

### ISSUE THREAD

**Issue by allaud** [bhauman/figwheel-main#84]
I'm trying to follow this instruction: https://github.com/bhauman/figwheel-main/blob/master/docs/docs/vim.md

On figwheel start I get this error:

      user=> (use 'figwheel.main)
      nil
      user=> (figwheel.main.api/start {:mode :serve} "dev")
      ClassNotFoundException figwheel.main.api  java.net.URLClassLoader.findClass (URLClassLoader.java:381)

P.S. Just in case - I'm using clojure:lein docker image

**Comment by bhauman** [comment]
I'd make sure you are using the latest version of figwheel.main 0.1.9

I'm assuming you are using Java 9/10?

**Comment by allaud** [comment]
@bhauman this is the project I'm trying to run: https://github.com/allaud/figwheel-main-skeleton

This is the command I'm using to run docker container (from the project root):

     docker run -v `pwd`:/app -w '/app' -p3449:3449 -p7888:7888 -it clojure:lein /bin/bash

This is the version info:

    root@1d6a709fb0c1:/app# java -version
    openjdk version "1.8.0_181"
    OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1~deb9u1-b13)
    OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
    root@1d6a709fb0c1:/app# javac -version
    javac 1.8.0_181

**Comment by allaud** [comment]
I guess there's a mistake in the docs and the actual command should be
`(require 'figwheel.main.api)`  instead of `(require 'figwheel.main)`

**Comment by bhauman** [comment]
Does this mean your issue is resolved?

**Comment by bhauman** [comment]
yeah it looks that that was the problem, if you can point out the docs that sent you the wrong way, I'll fix them straight away.
