### ISSUE TITLE
java.lang.ClassNotFoundException: org.eclipse.jetty.http.HttpParser$ProxyHandler

### ISSUE THREAD

**Issue by bhauman** [bhauman/figwheel-main#95]
This is an error caused by a dependency conflict with Jetty libraries in https://github.com/ring-clojure/ring/tree/master/ring-jetty-adapter and most commonly caused by including Datomic Cloud.

**Comment by bhauman** [comment]
The simple fix is to bring the Figwheel jetty deps inline with the Datomic Cloud Jetty deps:

```
com.datomic/client-cloud {:mvn/version "0.8.63"}
org.eclipse.jetty/jetty-server {:mvn/version "9.3.7.v20160115"}
org.eclipse.jetty.websocket/websocket-server {:mvn/version "9.3.7.v20160115"}
org.eclipse.jetty.websocket/websocket-servlet {:mvn/version "9.3.7.v20160115"}
```

These will effectively override the conflicting dependencies that are
in Figwheel and bring them inline with the Jetty libraries that are in
Datomic Cloud.

**Comment by bskinny** [comment]
[Thanks for figwheel @bhauman]

I'm seeing something similar when updating from ring 1.7.0 to 1.7.1:
java.lang.ClassNotFoundException: org.eclipse.jetty.util.ConcurrentArrayQueue

This can be reproduced with the figwheel template project (hello-world.app) by adding ring 1.7.1 as a dependency (ring 1.7.0 works fine). E.g. deps.edn:
```
{:deps {org.clojure/clojure {:mvn/version "1.9.0"}
        org.clojure/clojurescript {:mvn/version "1.10.439"}
        reagent {:mvn/version "0.8.1"}
        ring {:mvn/version "1.7.1"}}
 :paths ["src" "resources"]
 :aliases {:fig {:extra-deps
                  {com.bhauman/rebel-readline-cljs {:mvn/version "0.1.4"}
                   com.bhauman/figwheel-main {:mvn/version "0.1.9"}}
                 :extra-paths ["target" "test"]}
           :build {:main-opts ["-m" "figwheel.main" "-b" "dev" "-r"]}
           :min   {:main-opts ["-m" "figwheel.main" "-O" "advanced" "-bo" "dev"]}
           :test  {:main-opts ["-m" "figwheel.main" "-co" "test.cljs.edn" "-m" hello-world.test-runner]}}}
```

**Comment by bhauman** [comment]
Oh awesome there is a new version of ring out. 

This will fix these problems once and for all. Everyone should try the latest `com.bhauman/figwheel-main 0.2.1-SNAPSHOT`.

I just updated figwheel-main to use `ring 1.7.1` so this shouldn't be a problem unless you have other libraries that have conflicting versions of jetty dependencies.

Thanks @bskinny for letting me know.

**Comment by bskinny** [comment]
Much appreciated!

**Comment by antonmos** [comment]
0.2.1-SNAPSHOT is working well. Does it make sense to publish a final version now?
